### ISSUE TITLE
District Teams Invalid Endpoint

### ISSUE THREAD

**Issue by PChild** [frc1418/tbapy#10]
The endpoint for district_teams should be `district/{district_key}/teams` not `district/{district_key}/{year}/teams` like it is now. 

Didn't submit a PR since I wasn't sure if you'd prefer keeping parameters the same or changing them. 

If you keep the current parameters and have "chs" as a valid district key for example, it might be good to specify that; I tried pretty much every permutation of values from [this file](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/district_type.py) before realizing why I was getting errors.

**Comment by ErikBoesen** [comment]
@andrewl1 - take a shot at this. Shouldn't be too hard.

**Comment by andrewl1** [comment]
District keys appear to be the year number concatenated with the district abbreviation.
Chesapeake 2017 --> 2017chs

**Comment by ErikBoesen** [comment]
Fixed by #11.

**Comment by ErikBoesen** [comment]
[Done.](https://pypi.python.org/pypi/tbapy/1.2.2)
