### ISSUE TITLE
Pulling red or blue alliance data.

### ISSUE THREAD

**Issue by Tormenator1** [frc1418/tbapy#34]
Hello. I'd like to use this API to pull data for either red alliance or blue alliance in a certain match?
I don't see where that's done anywhere in the documentation. If it's possible,could you point to a example?
Thanks.

**Comment by ErikBoesen** [comment]
```py
match = tba.match('2017chcmp_sf2m1')
match['alliances']['red']  # -> gives you data about the red alliance
match['alliances']['blue']  # -> gives you data about the blue alliance
```
