### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by virtuald** [frc1418/tbapy#35]
When an error occurs, it's fairly difficult to figure out what went wrong (see https://github.com/frc1418/tbapy/issues/26).

The get/post methods should check the returned JSON for an 'errors' key, and if present raise an exception. The JSON returns something like this when an error is present:

```
{'Errors': [{'team_id': '294 is not a valid team id'}]}
```

**Comment by ErikBoesen** [comment]
@AndrewLester @JosephCarpenter Want to look at this?
