### ISSUE TITLE
event_predictions broken

### ISSUE THREAD

**Issue by mpaulonis** [frc1418/tbapy#38]
The event_predictions function is broken.  Running it returns an error of no object named Predictions.

In models.py, you have 

Prediction = _model_class('Prediction')

this needs to be

Predictions = _model_class('Predictions')

**Comment by ErikBoesen** [comment]
@AndrewLester

**Comment by ErikBoesen** [comment]
Fixed and released version 1.3.2 to PyPI.

**Comment by mpaulonis** [comment]
Thanks.  It's a very convenient wrapper package.  Appreciate the developers for making it available.
